# Generated by Django 3.2.6 on 2021-12-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=400, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('parent_picture', models.PositiveIntegerField()),
            ],
        ),
    ]
