# Generated by Django 3.2.6 on 2021-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211201_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent_picture',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Исходная фотография'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка'),
        ),
    ]
